Фикс небольших ошибок и неточностей в переводе
DenisMasterHerobrine/RotN-Translation pull request #3
Opened 2022-03-20 18:32 UTC by Suiranoil

2022-03-21 08:59 UTC, DenisMasterHerobrine requested changes
Привет, спасибо за помощь в улучшении перевода! В данном случае мне нравятся почти все изменения, но возникли некоторые вопросы относительно изменений в склонениях слов.

`patchouli_books/survivorshandbook/ru_ru/categories/equipment_trinkets.json` - сопротивление всё-таки куда лучше подходит здесь, поскольку ожерелья и снаряжение дают сопротивление урону или какие-то баффы, но не дают сопротивление чему-то ещё особому, кроме как урону. Может есть смысл сделать "сопротивление урону" тогда?
 
`patchouli_books/survivorshandbook/ru_ru/categories/magic_talismancy.json` - "предметы, которые дают мне магические эффекты и **защиту**", дают "защиты" - ошибка в падежной форме имени существительного.

2022-03-21 21:16 UTC, Suiranoil commented
1. "unique powers and **resistances**" - множественное число отсюда и перевод "уникальные силы и **сопротивления**"
Хотя, если ожерелья и снаряжение не дают других типов сопротивлений, кроме сопротивления урону, то можно и "сопротивление урону" использовать. Но с другой стороны, автор написал именно resistances, подразумевая, что могут быть различные виды, даже если их нет в игре по "лору" они вполне могли давать не только сопротивление урону.

2. "grant me magical effects and **protections**" - речь идет о защитах именно во множественном числе, соответственно в контексте перевода получаем "предметы, которые дают мне" винительный падеж. Слово "защита" во мн.ч. в.п - "защиты". Отсюда и такой вариант перевода "дают мне магические эффекты и **защиты**".

2022-03-23 12:00 UTC, DenisMasterHerobrine commented
Хорошо, тогда вполне всё устраивает. 👍

2022-03-23 12:00 UTC, DenisMasterHerobrine approved these changes

2022-03-23 12:03 UTC, merged